language: java
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success https://discord.com/api/webhooks/885153845481734236/awKKrNSIZK2NStnUsYVOidaxnd0hPbI1Goo5L8WeWCIGcPUvyVItJ3V8Z3DNGIjS5Q6z
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discord.com/api/webhooks/885153845481734236/awKKrNSIZK2NStnUsYVOidaxnd0hPbI1Goo5L8WeWCIGcPUvyVItJ3V8Z3DNGIjS5Q6z
